
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: pythontest
defaults:
  run:
    working-directory: ./bindings
jobs:
  wheel:
    name: python${{ matrix.python-version }}-${{ matrix.platform.python-architecture }} ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        python-version: [3.8] # This list needs to be kept in sync with maturin_build_wheel.py.
        platform: [
        { os: "ubuntu-latest",  python-architecture: "x64", rust-target: "x86_64-unknown-linux-gnu" },
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Download and Run Pravega standalone
        run: |
          wget https://github.com/pravega/pravega/releases/download/v0.8.0/pravega-0.8.0.tgz
          tar -xzvf pravega-0.8.0.tgz
          pravega-0.8.0/bin/pravega-standalone /dev/null 2>&1 &
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform.python-architecture }}
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          target: ${{ matrix.platform.rust-target }}
          override: true
          components: rustfmt, clippy
      - run: rustup set default-host ${{ matrix.platform.rust-target }}
      - name: install maturin
        run: pip install maturin virtualenv
      - name: create virtualenv
        run: |
          virtualenv venv
          source venv/bin/activate
          maturin develop
      - name: install tox
        run: pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
